version: "2"

services:
  application:
    image: debian
    volumes:
      - ./:/go/src/github.com/foo/bar
  api:
    image: dung13890/go-env
    restart: on-failure
    volumes_from:
      - application
    working_dir: /go/src/github.com/foo/bar
    environment:
      - GOBIN=/go/bin
    tty: true
